name: Build and Deploy

on:
  schedule:
    # 毎日9時（UTC）に実行
    - cron: '0 9 * * *'
  push:
    # mainブランチにプッシュされた場合も実行
    branches:
      - main
  workflow_dispatch: # 手動実行を可能にする

permissions:
  contents: write # GitHub Pagesへのデプロイに必要

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Build Go binary
        run: |
          go build -o event-grepper main.go

      - name: Run Go binary
        run: |
          ./event-grepper

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build React app
        run: |
          cd event-grepper-app # Reactアプリが置かれているディレクトリに移動
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./event-grepper-app/build
